# Generated by Django 3.2.12 on 2022-03-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_shirts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shirts',
            new_name='Shirt',
        ),
    ]
