# Generated by Django 3.2.12 on 2022-03-15 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
