# FILE: ci_ref_cicd.yml
# DATE (created): Oct 20, 2022
# PURPOSE: 
#  This GitAction workflow defines my CI/CD pipeline for this project. 

name: CI-REF-CI-CD

on:
  push:
    #branches: [ "master" ]
    #branches-ignore: ["master"]

  pull_request:
    #branches: [ "master", "develop" ]
    #branches-ignore: ["master"]

  # SR-ADD: Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Create custom CI/CD variables.
# Define custom workflow environment constants (ie. secrets etc.)
env:
  # TODO: Remember to update version on new tag
  LATEST_TAG: 1.0.0
  SSH_DIR_PATH: ~/.ssh/
  SSH_FILENAME_KEY: key_staging
  SSH_FILENAME_CONFIG: config

  DOCKER_DC_YAML_FILEPATH: ./docker-compose.yml
  DOCKER_CONTAINER_DJ_NAME: djdc_web_aa
  DOCKER_CONTAINER_DB_NAME: djdc_db_pgv13_aa
  REMOTE_DOCKER_DC_GITHUB: /home/ubuntu/projects/s_git/github/
  REMOTE_DOCKER_DC_DIR_TMP: tmp/
  REMOTE_DOCKER_DC_DIR_STAGING: staging/
  REMOTE_DOCKER_DC_YAML_FILE: docker-compose.yml
  #REMOTE_DOCKER_DC_YAML_FILEPATH_TMP: /home/ubuntu/projects/s_git/github/tmp/
  #REMOTE_DOCKER_DC_YAML_FILEPATH: /home/ubuntu/projects/s_git/github/staging/docker-compose.yml
  TIMED_DELAY: 5

jobs:

  # JOB-01.
  # PURPOSE: Build & Run Docker Compose Linux containers.
  # USE-CASE: Useful as a 'smoke' test to ensure that the created containers are active & functioning as expected.
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Job shell message (start).
      - name: MESSAGE (Pre).
        run: echo "Git Action Workflow - JOB 01 -  START..."

      # Dump GitHub context.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Show GitHub context specific parameter values.
      - name: Show select GitHub context specific parameter values only
        run: |
          echo "[EVENT]: ${{ github.event_name }}"
          echo "[BRANCH]: ${{ github.repository.default_branch }}"

      # Runs a single command using the runners shell - 01.
      - name: Show Docker version installed on the runner.
        run: docker --version

      # Runs a single command using the runners shell - 02.
      - name: Show Docker Compose version installed on the runner.
        run: docker-compose --version

      # DOCKER: Show active containers (pre).
      - name: DOCKER - Show active containers.
        run: docker ps -a

      # Job shell message (end).
      - name: MESSAGE (Post).
        run: echo "Git Action Workflow - JOB 01 - DONE."

  # JOB-02.
  # PURPOSE: Deploy repo. to the cloud server.
  # USE-CASE: Push source code updates.  
  DeployToServer:
    name: Deploy to the 'staging' environemnt.
    # IMPORTANT: Condition true only when commiting or merging into branch 'master'.
    if: github.event.ref == 'refs/heads/master'
    needs: [Build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # [GitHub Action]: Set/Assign the workflow environment. 
    environment:
      # Name must be identical (ie. case-sensitive).
      name: staging
      #url: 'http://test.myapp.com'
    # Set env variables at the 'job' level.
    env:
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_AWS_LS_STAGING }}
      REMOTE_HOST: ${{ secrets.HOST_DNS_AWS_LS_STAGING }}
      REMOTE_USER: ${{ secrets.USERNAME_AWS_LS_STAGING }}
      TARGET: ${{ secrets.TARGET_DIR_AWS_LS_STAGING }}
    timeout-minutes: 10
    steps:
      - name: MESSAGE (Start)
        run: echo "Performing deployment - STAGING - START..." 

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: SSH - Configure SSH
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_AWS_LS_STAGING }}
#          REMOTE_HOST: ${{ secrets.HOST_DNS_AWS_LS_STAGING }}
#          REMOTE_USER: ${{ secrets.USERNAME_AWS_LS_STAGING }}
#          TARGET: ${{ secrets.TARGET_DIR_AWS_LS_STAGING }}
        run: |
          echo "Start the ssh-agent in the background."
          ssh-agent -c
          echo "Create SSH directory."
          mkdir -p ${{ env.SSH_DIR_PATH }}
          ls -lah ${{ env.SSH_DIR_PATH }}
          echo "Create key file."
          echo "$SSH_PRIVATE_KEY" > ${{ env.SSH_DIR_PATH }}${{ env.SSH_FILENAME_KEY }}
          chmod 600 ${{ env.SSH_DIR_PATH }}${{ env.SSH_FILENAME_KEY }}
          ls -lah ${{ env.SSH_DIR_PATH }}
          cat >>${{ env.SSH_DIR_PATH }}${{ env.SSH_FILENAME_CONFIG }} <<END
          Host staging
            HostName $REMOTE_HOST
            User $REMOTE_USER
            IdentityFile ${{ env.SSH_DIR_PATH }}${{ env.SSH_FILENAME_KEY }}
            StrictHostKeyChecking no
          END
          ls -lah ${{ env.SSH_DIR_PATH }}
          cat ${{ env.SSH_DIR_PATH }}${{ env.SSH_FILENAME_KEY }}

#          echo "Start the ssh-agent in the background."
#          ssh-agent -c
#          echo "Create SSH directory."
#          mkdir -p ~/.ssh/
#          ls -lah ~/.ssh/
#          echo "Create key file."
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/key_staging
#          chmod 600 ~/.ssh/key_staging
#          ls -lah ~/.ssh/
#          cat >>~/.ssh/config <<END
#          Host staging
#            HostName $REMOTE_HOST
#            User $REMOTE_USER
#            IdentityFile ~/.ssh/key_staging
#            StrictHostKeyChecking no
#          END
#          ls -lah ~/.ssh/
#          cat ~/.ssh/key_staging

      # Show remote machine docker container info.
      - name: SSH - Verify remote server file structure
        run: |
          echo "REMOTE: List files & folders"
          ssh staging "sudo ls -lah"
          echo "REMOTE: Show all existing GitHub sub-directories (pre)"
          ssh staging "sudo ls -lah ${{ env.REMOTE_DOCKER_DC_GITHUB }}"
          echo "REMOTE: Create required sub-directory (only if it doesn't already exist)."
          ssh staging "mkdir -p ${{ env.REMOTE_DOCKER_DC_GITHUB }}${{ env.REMOTE_DOCKER_DC_DIR_TMP }}"
          echo "REMOTE: Show all existing GitHub sub-directories (post)"
          ssh staging "sudo ls -lah ${{ env.REMOTE_DOCKER_DC_GITHUB }}"

      # Show remote machine docker container info.
      - name: SSH - Show remote server Docker installation info
        run: |
          echo "REMOTE: Show Docker engine version."
          ssh staging "sudo docker --version"
          echo "REMOTE: Show Docker Compose version."
          ssh staging "sudo docker-compose --version"

      # Show remote machine docker container info.
      - name: SSH - Show all Docker container info/status (pre)
        run: |
          echo "REMOTE: Show all existing containers"
          ssh staging "sudo docker ps -a"

      # Deploy code with rsync over SSH.
      - name: Deploy to Server 01 - Staging
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_AWS_LS_STAGING }}
          REMOTE_HOST: ${{ secrets.HOST_DNS_AWS_LS_STAGING }}
          REMOTE_USER: ${{ secrets.USERNAME_AWS_LS_STAGING }}
          TARGET: "${{ env.REMOTE_DOCKER_DC_GITHUB }}${{ env.REMOTE_DOCKER_DC_DIR_TMP }}"

      # Build & Run the Docker container/services defined in the YAML file.
      - name: Build & Run Docker containers.
        run: |
          echo "${{ env.REMOTE_DOCKER_DC_GITHUB }}${{ env.REMOTE_DOCKER_DC_DIR_TMP }}"
          ssh staging "sudo docker-compose -f ${{ env.REMOTE_DOCKER_DC_GITHUB }}${{ env.REMOTE_DOCKER_DC_DIR_TMP }}${{ env.REMOTE_DOCKER_DC_YAML_FILE }} up -d"

      # Timed delayed for database to spin up.
      - name: Timed delay (DB spin up)
        run: |
          # Wait for database to be ready (IMPORTANT: Required for DB to spin up).
          echo "Wait for database to be ready (${{ env.TIMED_DELAY }}s)..."
          sleep $TIMED_DELAY

      # Show remote machine docker container info.
      - name: SSH - Show all Docker container info/status (post)
        run: |
          echo "REMOTE: Show all existing containers"
          ssh staging 'sudo docker ps -a'

      # Stop & remove the Docker container/services defined in the YAML file.
      - name: SSH - Cleanup - Stop & remove Docker containers.
        run: ssh staging "sudo docker-compose -f ${{ env.REMOTE_DOCKER_DC_GITHUB }}${{ env.REMOTE_DOCKER_DC_DIR_TMP }}${{ env.REMOTE_DOCKER_DC_YAML_FILE }} down"

      - name: MESSAGE (End)
        run: echo "Performing deployment - STAGING - DONE." 
